// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProject struct {
	Name string `json:"name"`
}

type NewScope struct {
	Colour   string `json:"colour"`
	Name     string `json:"name"`
	Progress string `json:"progress"`
}

type Project struct {
	ID    string   `json:"id"`
	Name  string   `json:"name"`
	Scope []*Scope `json:"scope"`
}

type ProjectList struct {
	Data       []*Project `json:"data"`
	HasMore    bool       `json:"has_more"`
	TotalCount int        `json:"total_count"`
}

type Scope struct {
	Colour   string `json:"colour"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Progress string `json:"progress"`
}
